name: Build ImmortalWrt Firmware 237

on:
  repository_dispatch:
  workflow_dispatch:
    inputs:
      ssh:
        description: SSH connection to Actions
        required: false
        default: 'false'

env:
  REPO_URL: https://github.com/padavanonly/immortalwrt-mt798x-6.6
  REPO_BRANCH: openwrt-24.10-6.6
  FEEDS_CONF: feeds.conf.default
  CONFIG_FILE: .config
  DIY_P1_SH: diy-part1.sh
  DIY_P2_SH: diy-part2.sh
  UPLOAD_FIRMWARE: true
  UPLOAD_RELEASE: true
  TZ: Asia/Shanghai

jobs:
  build:
    name: build-firmware
    runs-on: ubuntu-22.04
    permissions:
      contents: write
      actions: write
    
    steps:
      - name: 清理磁盘空间 (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          tool-cache: false
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: false

      - name: Checkout code
        uses: actions/checkout@v4

      - name: 安装编译环境
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo bash -c 'bash <(curl -sL https://build-scripts.immortalwrt.eu.org/init_build_environment.sh)'
          sudo -E apt-get -qq autoremove --purge
          sudo -E apt-get -qq clean
          sudo timedatectl set-timezone "$TZ"
          sudo mkdir -p /srcdir
          sudo chown $USER:$GROUPS /srcdir

      - name: 克隆源码仓库
        working-directory: /srcdir
        run: |
          echo "Free space:"
          df -hT $PWD
          git clone $REPO_URL -b $REPO_BRANCH openwrt
          ln -sf /srcdir/openwrt $GITHUB_WORKSPACE/openwrt

      - name: 更新feeds源
        run: cd openwrt && ./scripts/feeds update -a

      - name: 安装feeds & 执行diy-part1.sh
        run: | 
          cd openwrt && ./scripts/feeds install -a
          chmod +x $GITHUB_WORKSPACE/$SELF_BEFORE_SH
          $GITHUB_WORKSPACE/$SELF_BEFORE_SH

      - name: 加载配置 & 执行diy-part2.sh
        run: |
          [ -e files ] && mv files openwrt/files
          [ -e $CONFIG_FILE ] && mv $CONFIG_FILE openwrt/.config
          chmod +x $GITHUB_WORKSPACE/$SELF_AFTER_SH
          $GITHUB_WORKSPACE/$SELF_AFTER_SH

      - name: 下载软件包
        id: package
        run: |
          cd openwrt
          make defconfig
          make download -j8
          find dl -size -1024c -exec ls -l {} \;
          find dl -size -1024c -exec rm -f {} \;

      - name: 编译固件
        id: compile
        run: |
          cd openwrt
          echo -e "$(nproc) thread compile"
          make -j$(nproc) || make -j1 || make -j1 V=s
          echo "status=success" >> $GITHUB_OUTPUT
          echo "DEVICE_NAME=_xiaomi-ax3000t" >> $GITHUB_ENV
          echo "FILE_DATE=_$(date +"%Y%m%d%H%M")" >> $GITHUB_ENV

      - name: 检查磁盘空间
        if: (!cancelled())
        run: df -hT

      - name: 上传bin完整包 Artifact
        uses: actions/upload-artifact@v4
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          name: ImmortalWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: openwrt/bin

      - name: 整理固件路径
        id: organize
        if: (!cancelled())
        run: |
          cd openwrt/bin/targets/*/*
          rm -rf packages
          echo "FIRMWARE=$PWD" >> $GITHUB_ENV
          echo "status=success" >> $GITHUB_OUTPUT

      - name: 单独上传固件镜像 Artifact
        uses: actions/upload-artifact@v4
        if: steps.organize.outputs.status == 'success' && !cancelled()
        with:
          name: ImmortalWrt_firmware${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
          path: ${{ env.FIRMWARE }}

      - name: 生成Release说明文档
        id: make_release_note
        if: env.UPLOAD_RELEASE == 'true' && steps.compile.outputs.status == 'success'
        run: |
          echo "RELEASE_TAG=Build${{ env.FILE_DATE }}" >> $GITHUB_ENV
          echo "小米AX3000T-237 ImmortalWrt固件" > release_info.txt
          echo "后台地址：192.168.1.1" >> release_info.txt
          echo "账号：root" >> release_info.txt
          echo "密码：无" >> release_info.txt
          echo "默认主题：Bootstrap" >> release_info.txt
          echo "预装插件：argon、adguardhome、mtwifi-cfg" >> release_info.txt
          echo "其余插件可软件包手动安装" >> release_info.txt
          echo "编译源码：https://github.com/padavanonly/immortalwrt-mt798x-6.6" >> release_info.txt
          echo "release_ok=true" >> $GITHUB_OUTPUT

      - name: 发布 Release 上传固件
        id: release
        uses: softprops/action-gh-release@v2
        if: env.UPLOAD_RELEASE == 'true' && steps.make_release_note.outputs.release_ok == 'true'
        with:
          tag_name: ${{ env.RELEASE_TAG }}
          body_path: release_info.txt
          files: ${{ env.FIRMWARE }}/*
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 清理编译产物
        id: clean-compile
        run: |
          cd openwrt
          make clean

      - name: 缓存dl目录
        id: cache-compile
        uses: actions/cache/save@v4
        if: steps.compile.outputs.status == 'success' && !cancelled()
        with:
          path: openwrt/dl
          key: ${{ runner.os }}-openwrt-dl-${{ hashFiles('openwrt/feeds.conf.default') }}

      - name: 删除旧工作流运行记录
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 3
